spring:
  redis:
    database: 1
    host: 192.168.94.151
    port: 6379
    password: xuhaixing
    jedis:
      pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
    timeout: 5000
server:
  port: 8082