server:
  port: 8080
eureka:
  client:
    service-url:
     #\u6CE8\u518C\u5730\u5740
      defaultUrl: http://localhost:8761/eureka
spring:
  application:
    #\u4EE5\u540E\u7684\u670D\u52A1\u4E0E\u670D\u52A1\u4E4B\u95F4\u76F8\u4E92\u8C03\u7528\u4E00\u822C\u90FD\u662F\u6839\u636E\u8FD9\u4E2Aname
    name: eureka-client1
