com:
  xuhaixing:
    name: 徐海兴
    sex: 男
    all: ${com.xuhaixing.name},${com.xuhaixing.sex}
#server settings
server:
  port: 8081 #tomcat port
  address: 127.0.0.1   #access address
  session:
    timeout: 30
  context-path: /aaa   #contextPath 127.1.1.1：8081/aaa/*