spring:
  datasource:
    username: xuhaixing
    password: xuhaixing
    url: jdbc:mysql://192.168.94.151:3306/mytest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.xhx.springboot.entity
  config-location: classpath:mybatis/mybatis-config.xml
  type-handlers-package: com.xhx.springboot.convert
